name: CI Pipeline

on:
  pull_request:
    branches:
      - main  # Triggers the workflow on PR to the 'main' branch

jobs:
  test:
    runs-on: ubuntu-latest  # The CI pipeline will run on an Ubuntu machine

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2  # Checks out the repository code

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'  # Set the Python version to use

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip  # Cache the pip cache to avoid re-installing dependencies
        key: ${{ runner.os }}-python-${{ hashFiles('requirements.txt') }}  # Cache key based on the requirements file
        restore-keys: |
          ${{ runner.os }}-python-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip  # Upgrade pip to the latest version
        python -m venv venv                   # Create a virtual environment
        source venv/bin/activate              # Activate the virtual environment
        pip install -r requirements.txt      # Install dependencies from requirements.txt

    - name: Run tests
      run: |
        source venv/bin/activate  # Activate the virtual environment
        pytest --exitfirst --disable-warnings --maxfail=1 || exit 1  # Run pytest to execute all the tests
